
name: Task 15

on:
  pull_request:
    branches:
    - develop
    - main
  push:    
    branches:
    - develop
    - main

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fusion-energy/neutronics-workshop:base
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test task 15
        run: |
          pytest tests/test_task_15.py -v
